# Travis continuous integration

language: java

dist: trusty

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "intranda"
    token:
      secure: $SONAR_TOKEN

script:
  - cd goobi-viewer-connector
  - mvn install -B -V
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
