
	            package de.intranda.digiverso.m2m;
	            /*
	            DO NOT
	            CHANGE THIS FILE, IT'S GENERATED BY ANT!
	            */
	            public class Version {
	            public final static String VERSION = "Goobi viewer Connector v3.2";
	            public final static String BUILDVERSION = "158cd2d";
	            public final static String BUILDDATE = "20170130";
	            }
	        