
	            package io.goobi.viewer.connector;
	            /*
	            DO NOT
	            CHANGE THIS FILE, IT'S GENERATED BY ANT!
	            */
	            public class Version {
	            public final static String VERSION = "Goobi viewer Connector v3.4";
	            public final static String BUILDVERSION = "abcdefg";
	            public final static String BUILDDATE = "20190509";
	            }
	        