name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      name: Checkout Goobi viewer Connector

    - uses: actions/cache@v1
      name: Set up caching
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build connector.jar
      run: mvn -f goobi-viewer-connector/pom.xml clean package -U -B

